/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vsms;

import vsms.folder.MySqlConnect;
import vsms.folder.Car;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import static vsms.AddManufacturer.domain;

/**
 *
 * @author SAMI
 */
public class AddModel extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    static String domain;
    /**
     * Creates new form AddModel
     */
    public AddModel() {
        initComponents();
        show_car();
    }
    public ArrayList<Car> carList(){
        ArrayList<Car> carList = new ArrayList<>();
        try{
            conn= MySqlConnect.ConnectDB();
            String query = "SELECT models.id, manufacturers.manufacturer_name, models.model_name,models.model_description FROM models INNER JOIN manufacturers ON models.manufacturer_id = manufacturers.id";
            pst = conn.prepareStatement(query);
            rs = pst.executeQuery();
            Car car;
            while(rs.next()){
                car = new Car (rs.getInt("id"),rs.getString("manufacturer_name"),rs.getString("model_name"),rs.getString("model_description"));
                carList.add(car);
                
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
        return carList;
    }
    
    public void show_car(){
        ArrayList<Car> list = carList();
        DefaultTableModel model= (DefaultTableModel)carInformation.getModel();
        Object[] row = new Object[4];
        for(int i =0; i<list.size();i++){
            row[0]=list.get(i).getId();
            row[1]= list.get(i).getManufacturerName();
            row[2]= list.get(i).getModelName();
            row[3]= list.get(i).getDescription();
            
            model.addRow(row);
      
            
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addNewModel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carInformation = new javax.swing.JTable();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        dashboard = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        addEmployee = new javax.swing.JMenuItem();
        allEmployee = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        addManufacturer = new javax.swing.JMenuItem();
        addModel = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        allVechiles = new javax.swing.JMenuItem();
        soldVechiles = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addNewModel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addNewModel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insert.PNG"))); // NOI18N
        addNewModel.setText("ADD NEW MODEL");
        addNewModel.setBorder(new javax.swing.border.MatteBorder(null));
        addNewModel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNewModelMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("ALL CAR MODEL");

        carInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Model Name", "Menufacturer Nmae", "Description"
            }
        ));
        carInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carInformationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(carInformation);

        updateButton.setBackground(new java.awt.Color(153, 153, 153));
        updateButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.PNG"))); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(153, 153, 153));
        deleteButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.PNG"))); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addNewModel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(updateButton)
                .addGap(158, 158, 158)
                .addComponent(deleteButton)
                .addGap(0, 169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(addNewModel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 51, 51));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 5));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setAlignmentX(5.0F);
        jMenuBar1.setAlignmentY(5.0F);
        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(10, 10, 10, 10));

        dashboard.setBackground(new java.awt.Color(0, 102, 102));
        dashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 5));
        dashboard.setText("Dashboard     ");
        dashboard.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardActionPerformed(evt);
            }
        });
        jMenuBar1.add(dashboard);

        jMenu2.setBackground(new java.awt.Color(0, 51, 51));
        jMenu2.setText("Manage Employee     ");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        addEmployee.setText("Add Employee");
        addEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeActionPerformed(evt);
            }
        });
        jMenu2.add(addEmployee);

        allEmployee.setText("All Employee");
        allEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allEmployeeActionPerformed(evt);
            }
        });
        jMenu2.add(allEmployee);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Manufacturer & Model     ");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        addManufacturer.setText("Add Manufacturer");
        addManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addManufacturerActionPerformed(evt);
            }
        });
        jMenu3.add(addManufacturer);

        addModel.setText("Add Model");
        addModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addModelActionPerformed(evt);
            }
        });
        jMenu3.add(addModel);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Vechiles     ");
        jMenu4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        allVechiles.setText("All Vechiles");
        allVechiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allVechilesActionPerformed(evt);
            }
        });
        jMenu4.add(allVechiles);

        soldVechiles.setText("Sold Vechiles");
        soldVechiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soldVechilesActionPerformed(evt);
            }
        });
        jMenu4.add(soldVechiles);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        // TODO add your handling code here:
        Dashboard d = new Dashboard();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_dashboardActionPerformed

    private void addEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeActionPerformed
        // TODO add your handling code here:
        AddEmployee addemp = new AddEmployee();
        addemp.setVisible(true);
        dispose();
    }//GEN-LAST:event_addEmployeeActionPerformed

    private void allEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allEmployeeActionPerformed
        // TODO add your handling code here:
        AllEmployee allemp = new AllEmployee();
        allemp.setVisible(true);
        dispose();
    }//GEN-LAST:event_allEmployeeActionPerformed

    private void addManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addManufacturerActionPerformed
        // TODO add your handling code here:
        AddManufacturer manufacturer = new AddManufacturer();
        manufacturer.setVisible(true);
        dispose();
    }//GEN-LAST:event_addManufacturerActionPerformed

    private void addModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addModelActionPerformed
        // TODO add your handling code here:
        AddModel model = new AddModel();
        model.setVisible(true);
        dispose();
    }//GEN-LAST:event_addModelActionPerformed

    private void allVechilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allVechilesActionPerformed
        // TODO add your handling code here:
        AllVechiles allvechiles = new AllVechiles();
        allvechiles.setVisible(true);
        dispose();
    }//GEN-LAST:event_allVechilesActionPerformed

    private void soldVechilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soldVechilesActionPerformed
        // TODO add your handling code here:
        SoldVechiles soldvechiles = new SoldVechiles();
        soldvechiles.setVisible(true);
        dispose();
    }//GEN-LAST:event_soldVechilesActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
 //
    }//GEN-LAST:event_updateButtonActionPerformed

    private void addNewModelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewModelMouseClicked
        // TODO add your handling code here:
        AddNewModel addNewModel = new AddNewModel();
        addNewModel.setVisible(true);
        dispose();
    }//GEN-LAST:event_addNewModelMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
          conn= MySqlConnect.ConnectDB();
        int p = JOptionPane.showConfirmDialog(rootPane, "Do You really want to delete?", "Deleted", JOptionPane.YES_NO_OPTION);
        if(p==0){

        
        try{
            
            String delete = "delete from models where id ="+domain;
            pst = conn.prepareStatement(delete);
            //pst.setString(1, domain);

            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)carInformation.getModel();
            model.setRowCount(0);
            show_car();
            JOptionPane.showMessageDialog(null, "Delete Data Successfully");
           

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void carInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carInformationMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            
            DefaultTableModel model = (DefaultTableModel)carInformation.getModel();
            //int i = manufacturerInformation.getSelectedRow();
           //String domain;
            int[] row_indexes= carInformation.getSelectedRows();
            for(int i=0;i<row_indexes.length;i++){
            domain= carInformation.getValueAt(row_indexes[i], 0).toString();  
            //System.out.println( domain);
}
            
    

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_carInformationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddModel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addEmployee;
    private javax.swing.JMenuItem addManufacturer;
    private javax.swing.JMenuItem addModel;
    private javax.swing.JLabel addNewModel;
    private javax.swing.JMenuItem allEmployee;
    private javax.swing.JMenuItem allVechiles;
    private javax.swing.JTable carInformation;
    private javax.swing.JMenu dashboard;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem soldVechiles;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
